export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const HINT_UPDATE = 'HINT_UPDATE';
export const LEGEND_UPDATE = 'LEGEND_UPDATE';
export const DATE_RANGE_CHANGE = 'DATE_RANGE_CHANGE';
export const PEOPLE_GROUP_CHANGE = 'PEOPLE_GROUP_CHANGE';
export const PEOPLE_RANGE_CHANGE = 'PEOPLE_RANGE_CHANGE';

export const MENTIONED_PEOPLE_DATA_UPDATE = 'MENTIONED_PEOPLE_DATA_UPDATE';
export const PERSONALISED_PEOPLE_DATA_UPDATE = 'PERSONALISED_PEOPLE_DATA_UPDATE';

export const LOGIN_STATE_CHANGE = 'LOGIN_STATE_CHANGE';
export const USER_DETAILS_UPDATE = 'USER_DETAILS_UPDATE';