export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const HINT_UPDATE = 'HINT_UPDATE';
export const LEGEND_UPDATE = 'LEGEND_UPDATE';
export const DATE_RANGE_CHANGE = 'DATE_RANGE_CHANGE';
export const PEOPLE_GROUP_CHANGE = 'PEOPLE_GROUP_CHANGE';
export const PEOPLE_RANGE_CHANGE = 'PEOPLE_RANGE_CHANGE';

export const MENTIONED_PEOPLE_DATA_UPDATE = 'MENTIONED_PEOPLE_DATA_UPDATE';
export const PERSONALISED_PEOPLE_DATA_UPDATE = 'PERSONALISED_PEOPLE_DATA_UPDATE';
export const CONNECTED_PEOPLE_CHAIN_UPDATE = 'CONNECTED_PEOPLE_CHAIN_UPDATE';
export const CONNECTIONS_ROOT_CHANGE = 'CONNECTIONS_ROOT_CHANGE';
export const RELATED_CONTENT_SINGLE_UPDATE = 'RELATED_CONTENT_SINGLE_UPDATE';

export const LOGIN_STATE_CHANGE = 'LOGIN_STATE_CHANGE';
export const USER_DETAILS_UPDATE = 'USER_DETAILS_UPDATE';

//user
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

//people
export const MENTIONED_PEOPLE_REQUEST = 'MENTIONED_PEOPLE_REQUEST';
export const MENTIONED_PEOPLE_SUCCESS = 'MENTIONED_PEOPLE_SUCCESS';
export const MENTIONED_PEOPLE_FAILURE = 'MENTIONED_PEOPLE_FAILURE';

export const PERSONALISED_PEOPLE_REQUEST = 'PERSONALISED_PEOPLE_REQUEST';
export const PERSONALISED_PEOPLE_SUCCESS = 'PERSONALISED_PEOPLE_SUCCESS';
export const PERSONALISED_PEOPLE_FAILURE = 'PERSONALISED_PEOPLE_FAILURE';

//connections
export const SET_ROOT_CONNECTION = 'SET_ROOT_CONNECTION';
export const SET_ACTIVE_ROOT_CONNECTION = 'SET_ACTIVE_ROOT_CONNECTION';

export const CONNECTIONS_REQUEST = 'CONNECTIONS_REQUEST';
export const CONNECTIONS_SUCCESS = 'CONNECTIONS_SUCCESS';
export const CONNECTIONS_FAILURE = 'CONNECTIONS_FAILURE';

export const ADD_CONNECTION_ROOT = 'ADD_CONNECTION_ROOT';
export const RESET_CONNECTIONS = 'RESET_CONNECTIONS';
